In [1]:
import pandas as pd

In [2]:
cache = pd.read_pickle("datasets/feature_cache/features_unified.pkl")

In [3]:
cache.keys()

dict_keys(['paths', 'cv_features', 'cnn_features', 'grades', 'buckets', 'dataset'])

In [4]:
cache["cv_features"].shape

(11500, 20)

In [5]:
ls datasets/feature_cache

features_unified.csv      features_unified.parquet  features_unified.pkl

In [6]:
features = pd.read_parquet("datasets/feature_cache/features_unified.parquet")

In [7]:
features

,path,grade,bucket,bucket_name,cv_corner_mean,cv_corner_TL,cv_corner_TR,cv_corner_BL,cv_corner_BR,cv_edge_mean,...,cnn_502,cnn_503,cnn_504,cnn_505,cnn_506,cnn_507,cnn_508,cnn_509,cnn_510,cnn_511
0,datasets/unified/psa1/PSA-Grades-Baseball_psa1...,1,0,Poor (1-2),13.188162,8.504858,3.503422,37.832005,2.912364,56.843864,...,0.140641,0.998594,0.293409,1.291726,0.246072,0.365467,1.488549,0.731953,0.147275,0.012979
1,datasets/unified/psa1/PSA-Grades-Baseball_psa1...,1,0,Poor (1-2),6.102609,6.792891,5.042847,6.689111,5.885585,61.127148,...,0.037820,0.534711,0.666747,1.628192,0.022019,0.128577,0.901512,2.564440,0.066826,0.643090
2,datasets/unified/psa1/PSA-Grades-Baseball_psa1...,1,0,Poor (1-2),1.119285,0.153111,0.144695,2.506667,1.672667,90.824516,...,0.152117,0.385314,0.296724,1.088089,0.061936,0.387344,0.723945,1.277742,0.000000,0.506253
3,datasets/unified/psa1/PSA-Grades-Baseball_psa1...,1,0,Poor (1-2),5.191302,2.335037,0.874547,13.343112,4.212512,76.985077,...,0.262293,0.517325,0.466918,0.431771,0.027821,0.782813,0.559890,1.774777,0.109227,0.349443
4,datasets/unified/psa1/PSA-Grades-Baseball_psa1...,1,0,Poor (1-2),8.017791,11.399687,0.811244,17.621197,2.239036,56.665154,...,0.810940,0.419844,0.059865,1.073443,0.228755,0.673894,0.464076,2.319165,0.000000,1.467688
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11495,datasets/unified/psa10/PSA-Grades-Baseball_psa...,10,4,Mint (9-10),0.992498,2.267742,0.349969,1.186284,0.165998,57.714951,...,0.517791,0.562293,0.114524,0.857312,0.040043,0.154600,0.657133,1.444316,0.034421,0.376124
11496,datasets/unified/psa10/PSA-Grades-Baseball_psa...,10,4,Mint (9-10),17.032446,40.866238,7.155847,6.547351,13.560346,71.387428,...,1.033205,0.339350,0.891350,1.378069,0.219838,0.472628,0.395819,2.255715,0.014601,0.665502
11497,datasets/unified/psa10/PSA-Grades-Baseball_psa...,10,4,Mint (9-10),11.831714,39.205406,0.124192,5.896591,2.100667,77.670174,...,0.373447,0.212961,0.095332,1.324977,0.112643,1.671010,0.391687,3.166348,0.063514,1.175282
11498,datasets/unified/psa10/PSA-Grades-Baseball_psa...,10,4,Mint (9-10),0.262885,0.230642,0.185329,0.285891,0.349679,68.731888,...,0.013541,1.330025,0.267206,0.750523,0.309545,0.021635,0.715299,1.201844,0.009731,0.845382
11499,datasets/unified/psa10/PSA-Grades-Baseball_psa...,10,4,Mint (9-10),4.897603,4.730976,1.683955,5.638735,7.536746,79.650208,...,0.142908,0.668806,0.533598,1.386278,0.043637,0.026876,0.613335,2.044638,0.030533,0.353428

In [8]:
features[["grade", "bucket"]].drop_duplicates()

       grade  bucket
0          1       0
1150       2       0
2300       3       1
3450       4       1
4600       5       2
5750       6       2
6900       7       3
8050       8       3
9200       9       4
10350     10       4